### ISSUE TITLE
Pass additional parameter to template

### ISSUE THREAD

**Issue by strimo378** [bovender/PubmedParser#12]
Hi all,

Thank you for the wonderful MediaWiki extensions. I have a suggestion for a new feature:

It would be great if I could pass an additional parameter to the template. In my instance, I want to pass a URL to the template that provides a full-text link.

`{{#pmid:31685720|pmid31685720|url=https://www.jstage.jst.go.jp/article/endocrj/67/2/67_EJ19-0313/_html/-char/en}}`

PS: The feature that you can specify the template name with `{{#pmid:31685720|#templatename}}` is not documented.

**Comment by bovender** [comment]
Good suggestions, thanks. Would you be able to submit a pull request? If not, I can look into it :-)

**Comment by strimo378** [comment]
Hi Daniel,

thank you for the feedback.

I recently moved to a mediawiki hosting service, so I currently have no testing environment to implement it. I'll try to address it on a plain debian instance...

Two questions:

1. I am currently using it always with `{{#pmid:123|pmid123}}`. Would you mind if I add an option `{{#pmid:123|-}}` that automatically uses `"pmid" + id` as label?
2. I experienced that the pmc is sometimes wrong. Is that a known problem or maybe a misconfiguration of my hoster?

**Comment by strimo378** [comment]
Did you see my pull request?

**Comment by bovender** [comment]
Sorry for this taking so long. I finally got around to (manually) testing this. PR #13 is merged. Thanks again!
